const dirTree = require("directory-tree");
const tree = dirTree(".", {
  exclude: /node_modules|\.git/,
  extensions: /^((?!js).)*$/
});

let prefix = `https://github.com/lib-pku/libpku/tree/master/`;
function solve(e, depth) {
  let s = "";
  let res = [];
  if (depth == 1) {
    res.push(`## toc`);
  }
  if (e.type == "directory") {
    for (let i = 0; i < depth; ++i) s += "#";
    res.push(`${s} ${e.name}`);
  } else if (e.type == "file") {
    res.push(`[${e.name}](${prefix + encodeURIComponent(e.path)})`);
  }
  if (e.children) {
    e.children.forEach(ww => {
      if (ww && ww.name) res.push(solve(ww, depth + 1));
    });
  }
  return res.join("\n");
}

// console.log(solve(tree, 1));

let begin = `<html>
<body>
  <link rel="stylesheet" href="assets/css/index.css">
  <div class="inner">
    <a href="https://lib-pku.github.io/">
      <h1>lib-pku.github.io</h1>
    </a>
    <h2></h2>
    <a href="https://github.com/lib-pku" class="button"><small>Follow me on</small> GitHub</a>
  </div>
  <div id="content-wrapper">
    <div class="inner clearfix">
      <section id="main-content"><aside id="sidebar">`;

let sd = `</section>`;

let ed = `<p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</p>
    </div>
  </div>
</body>
</html>`;

var remark = require("remark");
var html = require("remark-html");
var toc = require("remark-toc");

remark()
  .use(toc)
  .use(html)
  .process(solve(tree, 1), function(err, file) {
    if (err) {
      console.error(err);
    }
    // console.log(file)
    console.log(
      begin + String(file).replace("<h1 id=", `</aside>` + "<h1 id=") + ed
    );
    // console.log(String(file))
  });
